development:
  adapter: async

test:
  adapter: async


# production:
# adapter: redis
# url: <%= ENV["REDISCLOUD_URL"] %>
# channel_prefix: pixel-playground_production

production:
  adapter: redis
  url: redis://redistogo:944216814069434d333ad7f36c4419ce@angelfish.redistogo.com:11359/
  host: angelfish.redistogo.com
  port: 11359
  password: 944216814069434d333ad7f36c4419ce
  channel_prefix: pixel_playground_production
